name: Free RDP Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Creating RDP Environment
      uses: vishalvshekkar/ubuntu-rdp@main
      with:
        ngrok_auth_token: ${{ secrets.NGROK_AUTH_TOKEN }}
        rdp_password: 'Password123'
